### ISSUE TITLE
AttributeError: Attribute 'use_wide_img' not found

### ISSUE THREAD

**Issue by Charlie0257** [clvrai/tarp#1]
When I run the command for training TARP-BC model in distracting DMControl, there is an error as follows:
`Traceback (most recent call last):`
`  File "/home/charlie/PycharmProjects/tarp/tarp/utils/general_utils.py", line 67, in __getattr__`
`    return self.__getitem__(attr)`
`KeyError: 'use_wide_img'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
`  File "/home/charlie/PycharmProjects/tarp/tarp/train.py", line 396, in <module>`
`    ModelTrainer(args=get_args())`
`  File "/home/charlie/PycharmProjects/tarp/tarp/train.py", line 54, in __init__`
`    self.logger, self.model, self.train_loader = self.build_phase(train_params, 'train')`
`  File "/home/charlie/PycharmProjects/tarp/tarp/train.py", line 292, in build_phase`
`    model = params.model_class(self.conf.model, logger)`
`  File "/home/charlie/PycharmProjects/tarp/tarp/models/tarp_bc_mdl.py", line 28, in __init__`
`    self.build_network()`
`  File "/home/charlie/PycharmProjects/tarp/tarp/models/tarp_bc_mdl.py", line 91, in build_network`
`    if self._hp.use_wide_img:`
`  File "/home/charlie/PycharmProjects/tarp/tarp/utils/general_utils.py", line 69, in __getattr__`
 `   raise AttributeError("Attribute %r not found" % attr)`
`AttributeError: Attribute 'use_wide_img' not found`

How to handle it?
Thanks

**Comment by kpertsch** [comment]
@junjungoal can you please check this?

**Comment by junjungoal** [comment]
@Charlie0257 
Sorry for late reply. Its attribute is no longer used and I forgot to remove it. Thank you very much for the issue. I will update the repo.

**Comment by junjungoal** [comment]
@Charlie0257 It's now resolved. I will close this issue.
